import Container from "@/components/Container";
import metaData from "@/utils/metadata";

export const metadata = metaData({
    title: "How We Protect Your Data - About",
    description: "",
});

const HowWeProtectYourDataPage = () => {
    return (
        <>
            <Container
                sx={{
                    background: "white",
                    mt: "20px",
                    pt: { mobile: 6, tablet: 8, desktop: 10 },
                    pb: { mobile: 5, tablet: 6, desktop: 8 },
                    px: { mobile: 3, tablet: 6, desktop: 8 },
                    color: "#1E2A4A",
                    fontSize: 18,
                    lineHeight: 1.7,
                }}>
                <h2>CRUK Data Protection and Access Information</h2>

                <p>
                    Our goal is to help researchers find and reuse data
                    generated by CRUK research projects, making every donation
                    work harder to cure cancer. The Data Hub provides an
                    overview of the datasets stored by research projects and
                    contains no sensitive patient data. Where the datasets
                    include sensitive patient data, access is heavily
                    controlled to make sure that the research is in the public
                    interest, that the minimum data is used by trusted people
                    in a safe setting, and that results do not disclose any
                    personal data.
                </p>

                <h3>Accessing Cancer Data</h3>
                <p>
                    Once researchers have found a dataset of interest, they can
                    use the Hub to request access. Many of these datasets
                    include sensitive patient data. For these, access is
                    guarded by a robust legal and ethical framework and
                    controlled by a Data Access Committee. There are strict
                    controls on how researchers can access health data
                    information. The purpose must be approved before anyone can
                    use the data, and they are only given access to the minimum
                    amount of data necessary.
                </p>

                <p>
                    The types of organisations that may use health data
                    include:
                </p>
                <ul>
                    <li>
                        Researchers: use data for research and innovation, such
                        as understanding causes of disease, improving diagnosis,
                        and developing new treatments.
                    </li>
                    <li>
                        NHS providers, charities, and commissioners: use data to
                        improve care, monitor trends and patterns in activity,
                        evaluate services, and support local planning.
                    </li>
                    <li>
                        Companies partnered with the NHS: may also take part in
                        some of these activities.
                    </li>
                </ul>

                <h3>Legal and Ethical Framework</h3>
                <p>
                    Using identifiable health data in research means following a
                    robust framework:
                </p>
                <ul>
                    <li>
                        Under common law confidentiality, researchers must
                        respect the trust placed in them by data subjects.
                    </li>
                    <li>
                        UK GDPR and the Data Protection Act 2018 require
                        personal data to be handled lawfully, fairly, and
                        transparently.
                    </li>
                </ul>
                <p>
                    This does not necessarily mean that researchers need
                    explicit consent to use patient data. For example, they may
                    be granted approval through a research ethics committee.
                </p>

                <h3>Lawful Basis for Cancer Research</h3>
                <p>
                    Most cancer research does not rely on individual consent as
                    the legal basis for processing data. Instead, organisations
                    often rely on:
                </p>
                <ul>
                    <li>
                        Public task - for institutions like universities or
                        public research bodies.
                    </li>
                    <li>
                        Legitimate interest - more commonly used by charities
                        or commercial research teams.
                    </li>
                </ul>
                <p>
                    For special category data such as cancer diagnoses,
                    treatment records, and genomic information, an additional
                    lawful condition must also be met under Article 9 of the UK
                    GDPR. Specifically, Article 9(2)(j) permits the processing
                    of special category data when it is necessary for scientific
                    research purposes, provided that appropriate safeguards are
                    in place in accordance with Article 89(1). These safeguards
                    include data minimisation, pseudonymisation, and strong
                    governance practices to protect individuals&apos; rights and
                    freedoms.
                </p>

                <h3>Secure Environments</h3>
                <p>
                    Personal data requires secure environments and specialist
                    knowledge to use responsibly.
                </p>
                <p>
                    Many of the datasets funded through CRUK are stored in
                    Trusted Research Environments (TREs) and Secure Data
                    Environments (SDEs), which offer a safe space to explore
                    these rich datasets without compromising privacy by
                    accessing and analysing data without downloading it or
                    compromising its security.
                </p>
            </Container>
        </>
    );
};

export default HowWeProtectYourDataPage;
