const INITIAL_FORM_SECTION = "Welcome & Guide";
const SUBMISSON_FORM_SECTION = "Make active";
const STRUCTURAL_METADATA_FORM_SECTION = "structuralMetadata";
const DATASET_FILTERS_FORM_SECTION = "Dataset Filters";
const DATASET_TYPE = "Dataset type";
const TEAM_ID_FIELD = "team_id";
const DATA_CUSTODIAN_ROR_FIELD = "identifier";
const DATA_CUSTODIAN_NAME = "Name of Data Custodian";
const PATIENT_PATHWAY_DESCRIPTION = "Patient pathway description";
const ASSOCIATED_PROJECT_GRANTS_LOCATION_PREFIX =
    "Associated Project Grants.";
const DATA_CUSTODIAN_FIELDS = [
    "Name of Data Custodian",
    "Organisation Description",
    "Organisation Logo",
    "Organisation Membership",
    "identifier",
];

const OTHER_DATA_TYPES_FORM_SECTION = "Other";
const ENTITY_RELATIONSHIP_DIAGRAM_FORM_SECTION = "Entity Relationship Diagram";
const COVERAGE_FORM_SECTION = "coverage";
const DATASET_TIMELINES_FORM_SECTION = "provenance";
const ACCESSIBILITY_FORM_SECTION = "accessibility";
const TOOLS_AND_PUBLICATIONS_FORM_SECTION = "enrichmentAndLinkage";
const OBSERVATIONS_FORM_SECTION = "observations";

export {
    INITIAL_FORM_SECTION,
    SUBMISSON_FORM_SECTION,
    STRUCTURAL_METADATA_FORM_SECTION,
    DATASET_FILTERS_FORM_SECTION,
    OTHER_DATA_TYPES_FORM_SECTION,
    ENTITY_RELATIONSHIP_DIAGRAM_FORM_SECTION,
    COVERAGE_FORM_SECTION,
    DATASET_TIMELINES_FORM_SECTION,
    ACCESSIBILITY_FORM_SECTION,
    TOOLS_AND_PUBLICATIONS_FORM_SECTION,
    OBSERVATIONS_FORM_SECTION,
    DATASET_TYPE,
    TEAM_ID_FIELD,
    DATA_CUSTODIAN_ROR_FIELD,
    DATA_CUSTODIAN_NAME,
    DATA_CUSTODIAN_FIELDS,
    PATIENT_PATHWAY_DESCRIPTION,
    ASSOCIATED_PROJECT_GRANTS_LOCATION_PREFIX,
};
